// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEHyEII-5BfvqKyefWyTuhRtsVirYhjR0',
    appId: '1:325244172612:web:b154ddfacf6a328c24bf11',
    messagingSenderId: '325244172612',
    projectId: 'educonnect-437c1',
    authDomain: 'educonnect-437c1.firebaseapp.com',
    storageBucket: 'educonnect-437c1.appspot.com',
    measurementId: 'G-7Y56NHQH4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60j4Et-XS2x7SkurwZaJi0hkwK9H19fY',
    appId: '1:325244172612:android:5a21fd67bcdcca6424bf11',
    messagingSenderId: '325244172612',
    projectId: 'educonnect-437c1',
    storageBucket: 'educonnect-437c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaizaAUnw-vTXbsIVvJOo-YSpCTAJiGyk',
    appId: '1:325244172612:ios:48f6adcdc8383f9124bf11',
    messagingSenderId: '325244172612',
    projectId: 'educonnect-437c1',
    storageBucket: 'educonnect-437c1.appspot.com',
    iosBundleId: 'com.example.educonnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaizaAUnw-vTXbsIVvJOo-YSpCTAJiGyk',
    appId: '1:325244172612:ios:4a474499bb1141ed24bf11',
    messagingSenderId: '325244172612',
    projectId: 'educonnect-437c1',
    storageBucket: 'educonnect-437c1.appspot.com',
    iosBundleId: 'com.example.educonnect.RunnerTests',
  );
}